defaults:
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

project_name: "ChessZero"

hydra:
  run:
    dir: .
  output_subdir: null
  hydra_logging:
    level: ERROR

preprocessing:
  states_per_file: 500
  min_half_moves: 40
  min_elo: 2400
  game_count: 20

model:
  depth: 7
  filter_count: 256

mcts:
  simulations: 2

buffer:
  size: 10000
  min_size: 2000

train:
  num_epochs: 15
  batch_size: 4
  seed: 42
  worker_count: 10
  num_records: 1000
  learning_rate: 0.001
  drop_remainder: False
  self_play_steps: 200
  iterations: 10

interface:
  start_player: white