defaults:
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

project_name: "HnefataflZero"

hydra:
  run:
    dir: .
  output_subdir: null
  hydra_logging:
    level: ERROR

model:
  depth: 7
  filter_count: 256

mcts:
  simulations: 50

buffer:
  size: 10000
  min_size: 2000

train:
  num_epochs: 15
  batch_size: 128
  seed: 42
  worker_count: 10
  learning_rate: 0.001
  self_play_steps: 512
  iterations: 10
  max_eval_pool: 20
  load_checkpoint: False

interface:
  start_player: white